stages:
    - build
    - scan

build_getdata:
    stage: build
    tags:
        - aws
    script:
        - cd getdataservice
        - docker build -t getdata:$CI_PIPELINE_ID .

build_forecast:
    stage: build
    tags:
        - aws
    script:
        - cd forecastservice
        - docker build -t forecast:$CI_PIPELINE_ID .

scan_trivy:
    stage: scan
    tags:
        - aws
    script:
        - trivy --severity HIGH,CRITICAL --light --no-progress --exit-code 1 --cache-dir .trivycache/ getdata:$CI_PIPELINE_ID
        - trivy --severity HIGH,CRITICAL --light --no-progress --exit-code 1 --cache-dir .trivycache/ forecast:$CI_PIPELINE_ID
